"""
Copyright (C) 2026 Christoph Medicus
https://dev.betakontext.de
dev@betakontext.de

This file is part of SplitForge, a fork of SnapSplit by Christoph Medicus.

SplitForge is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see <https://www.gnu.org/licenses>.
"""

# localization.py
"""Translations of the UI (Blender's bpy.app.translations; registered in __init__.py).

Keys are (context, English msgid). Phase 3 removed the legacy SnapSplit UI and with it every
entry whose msgid no longer occurs in the add-on; the SplitForge UI (operator labels, property
and enum names, panel labels) is translated to German and Korean. Other locales keep the
remaining shared entries. Tooltips (descriptions) are not translated yet.
"""

DICTIONARY = {
    "de_DE": {
        ("*", "Dowel layout"): "Dübel-Anordnung",
        ("*", "Flat"): "Liegend",
        ("*", "Upright"): "Stehend",
        ("*", "At assembly position"): "In Einbaulage",
        ("*", "Accurate"): "Genau",
        ("*", "Active connector"): "Aktiver Verbinder",
        ("*", "Active cut"): "Aktiver Schnitt",
        ("*", "Add a cut (X/Y/Z or stroke), then Build"): "Schnitt hinzufügen (X/Y/Z oder Strich), dann Erzeugen",
        ("*", "Add Connector"): "Verbinder hinzufügen",
        ("Operator", "Add Connector"): "Verbinder hinzufügen",
        ("*", "Add Plane Cut"): "Ebenenschnitt hinzufügen",
        ("Operator", "Add Plane Cut"): "Ebenenschnitt hinzufügen",
        ("*", "Add Stroke Cut"): "Strichschnitt hinzufügen",
        ("Operator", "Add Stroke Cut"): "Strichschnitt hinzufügen",
        ("*", "Adjust Cut Plane"): "Schnittebene anpassen",
        ("Operator", "Adjust Cut Plane"): "Schnittebene anpassen",
        ("*", "Adjust in Viewport"): "Im Viewport anpassen",
        ("*", "Auto"): "Automatisch",
        ("*", "Auto Connectors"): "Automatische Verbinder",
        ("Operator", "Auto Connectors"): "Automatische Verbinder",
        ("*", "Axis"): "Achse",
        ("*", "Booleans"): "Boolesche Operationen",
        ("*", "both sides"): "beide Seiten",
        ("*", "Build"): "Erzeugen",
        ("Operator", "Build"): "Erzeugen",
        ("*", "Build & Export"): "Erzeugen & Exportieren",
        ("Operator", "Build & Export"): "Erzeugen & Exportieren",
        ("*", "Bump diameter (mm)"): "Noppendurchmesser (mm)",
        ("*", "Bump height (mm)"): "Noppenhöhe (mm)",
        ("*", "Bumps"): "Noppen",
        ("*", "Cannot build this cut:"): "Dieser Schnitt kann nicht erzeugt werden:",
        ("*", "Cap"): "Verschließen",
        ("*", "Chamfer (mm)"): "Fase (mm)",
        ("*", "Check Mesh"): "Mesh prüfen",
        ("Operator", "Check Mesh"): "Mesh prüfen",
        ("*", "Clear Build"): "Ergebnis entfernen",
        ("Operator", "Clear Build"): "Ergebnis entfernen",
        ("*", "Clear Stack"): "Stapel leeren",
        ("Operator", "Clear Stack"): "Stapel leeren",
        ("*", "Clearance (mm)"): "Spiel (mm)",
        ("*", "Click"): "Klicken",
        ("*", "Connector"): "Verbinder",
        ("*", "Connectors"): "Verbinder",
        ("Operator", "Connectors"): "Verbinder",
        ("*", "Count"): "Anzahl",
        ("*", "Custom"): "Eigen",
        ("*", "Custom mesh"): "Eigenes Mesh",
        ("*", "Cut"): "Schnitt",
        ("*", "Cylinder pin"): "Zylinderstift",
        ("*", "Debug log"): "Debug-Protokoll",
        ("*", "Direction"): "Richtung",
        ("*", "Distribute"): "Verteilen",
        ("*", "Distribution"): "Verteilung",
        ("*", "Dovetail"): "Schwalbenschwanz",
        ("*", "Dowel"): "Dübel",
        ("*", "Dowel (separate part)"): "Dübel (eigenes Teil)",
        ("*", "Down"): "Nach unten",
        ("*", "Draft"): "Entwurf",
        ("*", "Draw Cut"): "Schnitt zeichnen",
        ("*", "Duplicate Cut"): "Schnitt duplizieren",
        ("Operator", "Duplicate Cut"): "Schnitt duplizieren",
        ("*", "Easy"): "Einfach",
        ("*", "Easy Cut"): "Einfacher Schnitt",
        ("Operator", "Easy Cut"): "Einfacher Schnitt",
        ("*", "Editing the source's cuts"): "Bearbeitet die Schnitte der Quelle",
        ("*", "Enabled"): "Aktiv",
        ("*", "Explicit plane"): "Explizite Ebene",
        ("*", "Export Parts"): "Teile exportieren",
        ("Operator", "Export Parts"): "Teile exportieren",
        ("*", "Fast"): "Schnell",
        ("*", "Folder"): "Ordner",
        ("*", "Formats"): "Formate",
        ("*", "Gap (mm)"): "Fuge (mm)",
        ("*", "Grid"): "Raster",
        ("*", "Height (mm)"): "Höhe (mm)",
        ("*", "Index"): "Index",
        ("*", "Insert depth %"): "Einstecktiefe %",
        ("*", "Kind"): "Art",
        ("*", "Length (mm)"): "Länge (mm)",
        ("*", "Line"): "Linie",
        ("*", "Margin %"): "Rand %",
        ("*", "Material"): "Material",
        ("*", "Mesh"): "Mesh",
        ("*", "Mode"): "Modus",
        ("*", "Move Cut"): "Schnitt verschieben",
        ("Operator", "Move Cut"): "Schnitt verschieben",
        ("*", "New connector"): "Neuer Verbinder",
        ("*", "New connectors"): "Neue Verbinder",
        ("*", "Normal"): "Normale",
        ("*", "Offset (mm)"): "Versatz (mm)",
        ("*", "Origin"): "Ursprung",
        ("*", "Pin"): "Stift",
        ("*", "pin"): "Stift",
        ("*", "Pin on"): "Stift an",
        ("*", "Pin side"): "Stiftseite",
        ("*", "Place Connectors"): "Verbinder platzieren",
        ("Operator", "Place Connectors"): "Verbinder platzieren",
        ("*", "Plane"): "Ebene",
        ("*", "Point"): "Punkt",
        ("*", "Rectangular tenon"): "Rechteckzapfen",
        ("*", "Redraw in Viewport"): "Im Viewport neu zeichnen",
        ("*", "Remove Connector"): "Verbinder entfernen",
        ("Operator", "Remove Connector"): "Verbinder entfernen",
        ("*", "Remove Cut"): "Schnitt entfernen",
        ("Operator", "Remove Cut"): "Schnitt entfernen",
        ("*", "Replace"): "Ersetzen",
        ("*", "Result"): "Ergebnis",
        ("*", "Rotation"): "Drehung",
        ("*", "Rows"): "Reihen",
        ("*", "Select a mesh object"): "Ein Mesh-Objekt auswählen",
        ("*", "Settings"): "Einstellungen",
        ("Operator", "Settings"): "Einstellungen",
        ("*", "Show cuts in viewport"): "Schnitte im Viewport zeigen",
        ("*", "Smooth"): "Glätten",
        ("*", "Snap dovetail"): "Schnapp-Schwalbenschwanz",
        ("*", "Snap pin"): "Schnappstift",
        ("*", "Snap tenon"): "Schnappzapfen",
        ("*", "Snap to axis"): "An Achse ausrichten",
        ("*", "Stroke"): "Strich",
        ("*", "Tangent"): "Tangente",
        ("*", "Taper %"): "Verjüngung %",
        ("*", "Target"): "Ziel",
        ("*", "Tenon"): "Zapfen",
        ("*", "Transforms"): "Transformationen",
        ("*", "Type"): "Typ",
        ("*", "U (mm)"): "U (mm)",
        ("*", "Up"): "Nach oben",
        ("*", "Use Object Size"): "Objektgröße übernehmen",
        ("Operator", "Use Object Size"): "Objektgröße übernehmen",
        ("*", "V (mm)"): "V (mm)",
        ("*", "Width (mm)"): "Breite (mm)",
        ("*", "Write millimeters"): "In Millimetern schreiben",
    },
    "fr_FR": {
        ("*", "Auto"): "Auto",
        ("*", "Chamfer (mm)"): "Chanfrein (mm)",
        ("*", "Distribution"): "Répartition",
        ("*", "Dovetail"): "Queue d'aronde",
        ("*", "Grid"): "Grille",
        ("*", "Line"): "Ligne",
    },
    "es": {
        ("*", "Auto"): "Automático",
        ("*", "Chamfer (mm)"): "Chaflán (mm)",
        ("*", "Distribution"): "Distribución",
        ("*", "Dovetail"): "Cola de milano",
        ("*", "Grid"): "Cuadrícula",
        ("*", "Line"): "Línea",
    },
    "it_IT": {
        ("*", "Auto"): "Automatico",
        ("*", "Chamfer (mm)"): "Smusso (mm)",
        ("*", "Distribution"): "Distribuzione",
        ("*", "Dovetail"): "Coda di rondine",
        ("*", "Grid"): "Griglia",
        ("*", "Line"): "Linea",
    },
    "pt_BR": {
        ("*", "Auto"): "Automático",
        ("*", "Chamfer (mm)"): "Chanfro (mm)",
        ("*", "Distribution"): "Distribuição",
        ("*", "Dovetail"): "Rabo de andorinha",
        ("*", "Grid"): "Grade",
        ("*", "Line"): "Linha",
    },
    "pt_PT": {
        ("*", "Auto"): "Automático",
        ("*", "Chamfer (mm)"): "Chanfro (mm)",
        ("*", "Distribution"): "Distribuição",
        ("*", "Dovetail"): "Cauda de andorinha",
        ("*", "Grid"): "Grelha",
        ("*", "Line"): "Linha",
    },
    "nl_NL": {
        ("*", "Auto"): "Automatisch",
        ("*", "Chamfer (mm)"): "Afschuining (mm)",
        ("*", "Distribution"): "Verdeling",
        ("*", "Dovetail"): "Zwaluwstaart",
        ("*", "Grid"): "Raster",
        ("*", "Line"): "Lijn",
    },
    "pl_PL": {
        ("*", "Auto"): "Automatyczny",
        ("*", "Chamfer (mm)"): "Fazowanie (mm)",
        ("*", "Distribution"): "Rozmieszczenie",
        ("*", "Dovetail"): "Jaskółczy ogon",
        ("*", "Grid"): "Siatka",
        ("*", "Line"): "Linia",
    },
    "ja_JP": {
        ("*", "Auto"): "自動",
        ("*", "Chamfer (mm)"): "面取り (mm)",
        ("*", "Distribution"): "分布",
        ("*", "Dovetail"): "あり継ぎ",
        ("*", "Grid"): "グリッド",
        ("*", "Line"): "ライン",
    },
    "zh_HANS": {
        ("*", "Auto"): "自动",
        ("*", "Chamfer (mm)"): "倒角 (mm)",
        ("*", "Distribution"): "分布",
        ("*", "Dovetail"): "燕尾",
        ("*", "Grid"): "网格",
        ("*", "Line"): "直线",
    },
    "zh_HANT": {
        ("*", "Auto"): "自動",
        ("*", "Chamfer (mm)"): "倒角 (mm)",
        ("*", "Distribution"): "分佈",
        ("*", "Dovetail"): "燕尾",
        ("*", "Grid"): "網格",
        ("*", "Line"): "直線",
    },
    "ru_RU": {
        ("*", "Auto"): "Авто",
        ("*", "Chamfer (mm)"): "Фаска (мм)",
        ("*", "Distribution"): "Распределение",
        ("*", "Dovetail"): "Ласточкин хвост",
        ("*", "Grid"): "Сетка",
        ("*", "Line"): "Линия",
    },
    "uk_UA": {
        ("*", "Auto"): "Авто",
        ("*", "Distribution"): "Розподіл",
        ("*", "Dovetail"): "Ластівчин хвіст",
    },
    "tr_TR": {
        ("*", "Auto"): "Otomatik",
        ("*", "Distribution"): "Dağıtım",
        ("*", "Dovetail"): "Kırlangıç Kuyruğu",
    },
    "sl": {
        ("*", "Auto"): "Samodejno",
        ("*", "Chamfer (mm)"): "Faza (mm)",
        ("*", "Distribution"): "Porazdelitev",
        ("*", "Dovetail"): "Lastovičji rep",
        ("*", "Grid"): "Mreža",
        ("*", "Line"): "Črta",
    },
    "ko_KR": {
        ("*", "Dowel layout"): "도웰 배치",
        ("*", "Flat"): "눕혀서",
        ("*", "Upright"): "세워서",
        ("*", "At assembly position"): "조립 위치",
        ("*", "Accurate"): "정확",
        ("*", "Active connector"): "활성 커넥터",
        ("*", "Active cut"): "활성 컷",
        ("*", "Add a cut (X/Y/Z or stroke), then Build"): "컷을 추가(X/Y/Z 또는 스트로크)한 뒤 빌드",
        ("*", "Add Connector"): "커넥터 추가",
        ("Operator", "Add Connector"): "커넥터 추가",
        ("*", "Add Plane Cut"): "평면 컷 추가",
        ("Operator", "Add Plane Cut"): "평면 컷 추가",
        ("*", "Add Stroke Cut"): "스트로크 컷 추가",
        ("Operator", "Add Stroke Cut"): "스트로크 컷 추가",
        ("*", "Adjust Cut Plane"): "컷 평면 조정",
        ("Operator", "Adjust Cut Plane"): "컷 평면 조정",
        ("*", "Adjust in Viewport"): "뷰포트에서 조정",
        ("*", "Auto"): "자동",
        ("*", "Auto Connectors"): "자동 커넥터",
        ("Operator", "Auto Connectors"): "자동 커넥터",
        ("*", "Axis"): "축",
        ("*", "Booleans"): "불리언",
        ("*", "both sides"): "양쪽",
        ("*", "Build"): "빌드",
        ("Operator", "Build"): "빌드",
        ("*", "Build & Export"): "빌드 및 내보내기",
        ("Operator", "Build & Export"): "빌드 및 내보내기",
        ("*", "Bump diameter (mm)"): "돌기 지름 (mm)",
        ("*", "Bump height (mm)"): "돌기 높이 (mm)",
        ("*", "Bumps"): "돌기 수",
        ("*", "Cannot build this cut:"): "이 컷을 빌드할 수 없음:",
        ("*", "Cap"): "단면 막기",
        ("*", "Chamfer (mm)"): "모따기 (mm)",
        ("*", "Check Mesh"): "메시 검사",
        ("Operator", "Check Mesh"): "메시 검사",
        ("*", "Clear Build"): "빌드 지우기",
        ("Operator", "Clear Build"): "빌드 지우기",
        ("*", "Clear Stack"): "스택 비우기",
        ("Operator", "Clear Stack"): "스택 비우기",
        ("*", "Clearance (mm)"): "공차 (mm)",
        ("*", "Click"): "클릭",
        ("*", "Connector"): "커넥터",
        ("*", "Connectors"): "커넥터",
        ("Operator", "Connectors"): "커넥터",
        ("*", "Count"): "개수",
        ("*", "Custom"): "사용자",
        ("*", "Custom mesh"): "사용자 메시",
        ("*", "Cut"): "컷",
        ("*", "Cylinder pin"): "원기둥 핀",
        ("*", "Debug log"): "디버그 로그",
        ("*", "Direction"): "방향",
        ("*", "Distribute"): "자동 배치",
        ("*", "Distribution"): "분포",
        ("*", "Dovetail"): "도브테일",
        ("*", "Dowel"): "도웰",
        ("*", "Dowel (separate part)"): "도웰 (별도 파트)",
        ("*", "Down"): "아래로",
        ("*", "Draft"): "드래프트",
        ("*", "Draw Cut"): "컷 그리기",
        ("*", "Duplicate Cut"): "컷 복제",
        ("Operator", "Duplicate Cut"): "컷 복제",
        ("*", "Easy"): "간편",
        ("*", "Easy Cut"): "간편 컷",
        ("Operator", "Easy Cut"): "간편 컷",
        ("*", "Editing the source's cuts"): "원본의 컷을 편집 중",
        ("*", "Enabled"): "사용",
        ("*", "Explicit plane"): "평면 직접 지정",
        ("*", "Export Parts"): "파트 내보내기",
        ("Operator", "Export Parts"): "파트 내보내기",
        ("*", "Fast"): "빠름",
        ("*", "Folder"): "폴더",
        ("*", "Formats"): "형식",
        ("*", "Gap (mm)"): "틈 (mm)",
        ("*", "Grid"): "격자",
        ("*", "Height (mm)"): "높이 (mm)",
        ("*", "Index"): "인덱스",
        ("*", "Insert depth %"): "삽입 깊이 %",
        ("*", "Kind"): "종류",
        ("*", "Length (mm)"): "길이 (mm)",
        ("*", "Line"): "선",
        ("*", "Margin %"): "여백 %",
        ("*", "Material"): "재질",
        ("*", "Mesh"): "메시",
        ("*", "Mode"): "모드",
        ("*", "Move Cut"): "컷 이동",
        ("Operator", "Move Cut"): "컷 이동",
        ("*", "New connector"): "새 커넥터",
        ("*", "New connectors"): "새 커넥터",
        ("*", "Normal"): "법선",
        ("*", "Offset (mm)"): "오프셋 (mm)",
        ("*", "Origin"): "원점",
        ("*", "Pin"): "핀",
        ("*", "pin"): "핀",
        ("*", "Pin on"): "핀 위치",
        ("*", "Pin side"): "핀 쪽",
        ("*", "Place Connectors"): "커넥터 배치",
        ("Operator", "Place Connectors"): "커넥터 배치",
        ("*", "Plane"): "평면",
        ("*", "Point"): "점",
        ("*", "Rectangular tenon"): "사각 테논",
        ("*", "Redraw in Viewport"): "뷰포트에서 다시 그리기",
        ("*", "Remove Connector"): "커넥터 삭제",
        ("Operator", "Remove Connector"): "커넥터 삭제",
        ("*", "Remove Cut"): "컷 삭제",
        ("Operator", "Remove Cut"): "컷 삭제",
        ("*", "Replace"): "교체",
        ("*", "Result"): "결과",
        ("*", "Rotation"): "회전",
        ("*", "Rows"): "행",
        ("*", "Select a mesh object"): "메시 오브젝트를 선택하세요",
        ("*", "Settings"): "설정",
        ("Operator", "Settings"): "설정",
        ("*", "Show cuts in viewport"): "뷰포트에 컷 표시",
        ("*", "Smooth"): "다듬기",
        ("*", "Snap dovetail"): "스냅 도브테일",
        ("*", "Snap pin"): "스냅 핀",
        ("*", "Snap tenon"): "스냅 테논",
        ("*", "Snap to axis"): "축에 맞춤",
        ("*", "Stroke"): "스트로크",
        ("*", "Tangent"): "접선",
        ("*", "Taper %"): "테이퍼 %",
        ("*", "Target"): "대상",
        ("*", "Tenon"): "테논",
        ("*", "Transforms"): "변환",
        ("*", "Type"): "종류",
        ("*", "U (mm)"): "U (mm)",
        ("*", "Up"): "위로",
        ("*", "Use Object Size"): "오브젝트 크기 사용",
        ("Operator", "Use Object Size"): "오브젝트 크기 사용",
        ("*", "V (mm)"): "V (mm)",
        ("*", "Width (mm)"): "폭 (mm)",
        ("*", "Write millimeters"): "밀리미터로 쓰기",
    },
    "sw": {
        ("*", "Auto"): "Otomatiki",
        ("*", "Chamfer (mm)"): "Ukingo ulionyooshwa (mm)",
        ("*", "Distribution"): "Usambazaji",
        ("*", "Dovetail"): "Dovetail",
        ("*", "Grid"): "Gridi",
        ("*", "Line"): "Mstari",
    },
    "ar_EG": {
        ("*", "Auto"): "تلقائي",
        ("*", "Chamfer (mm)"): "الشطف (مم)",
        ("*", "Distribution"): "التوزيع",
        ("*", "Dovetail"): "ذيل الحمامة",
        ("*", "Grid"): "شبكة",
        ("*", "Line"): "خط",
    },
    "fa_IR": {
        ("*", "Auto"): "خودکار",
        ("*", "Chamfer (mm)"): "پخ (mm)",
        ("*", "Distribution"): "توزیع",
        ("*", "Dovetail"): "دم‌چلچله‌ای",
        ("*", "Grid"): "شبکه",
        ("*", "Line"): "خط",
    },
    "hi_IN": {
        ("*", "Auto"): "स्वचालित",
        ("*", "Chamfer (mm)"): "चम्फर (मिमी)",
        ("*", "Distribution"): "वितरण",
        ("*", "Dovetail"): "डवटेल",
        ("*", "Grid"): "ग्रिड",
        ("*", "Line"): "रेखा",
    },
}
