"""
Copyright (C) 2026 Christoph Medicus
https://dev.betakontext.de
dev@betakontext.de

This file is part of SplitForge, a fork of SnapSplit by Christoph Medicus.

SplitForge is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see <https://www.gnu.org/licenses>.
"""

# localization.py
"""Translations of the UI (Blender's bpy.app.translations; registered in __init__.py).

Keys are (context, English msgid). Phase 3 removed the legacy SnapSplit UI and with it every
entry whose msgid no longer occurs in the add-on; the SplitForge UI (operator labels, property
and enum names, panel labels) is translated to German and Korean. Other locales keep the
remaining shared entries. Tooltips (descriptions) are translated to Korean only (German keeps
English tooltips, by the user's choice). Labels with values use templates ("Part of {name}")
translated in Python (ui/panel.py tr()).
"""

DICTIONARY = {
    "de_DE": {
        ("*", "Stroke: {n} points"): "Strich: {n} Punkte",
        ("*", "Dowel layout"): "Dübel-Anordnung",
        ("*", "Flat"): "Liegend",
        ("*", "Upright"): "Stehend",
        ("*", "At assembly position"): "In Einbaulage",
        ("*", "Accurate"): "Genau",
        ("*", "Active connector"): "Aktiver Verbinder",
        ("*", "Active cut"): "Aktiver Schnitt",
        ("*", "Add a cut (X/Y/Z, stroke, polyline or polygon), then Build"): "Schnitt hinzufügen (X/Y/Z, Strich, Polylinie oder Polygon), dann Erzeugen",
        ("*", "Add Connector"): "Verbinder hinzufügen",
        ("Operator", "Add Connector"): "Verbinder hinzufügen",
        ("*", "Add Plane Cut"): "Ebenenschnitt hinzufügen",
        ("Operator", "Add Plane Cut"): "Ebenenschnitt hinzufügen",
        ("*", "Add Stroke Cut"): "Strichschnitt hinzufügen",
        ("Operator", "Add Stroke Cut"): "Strichschnitt hinzufügen",
        ("*", "Adjust Cut Plane"): "Schnittebene anpassen",
        ("Operator", "Adjust Cut Plane"): "Schnittebene anpassen",
        ("*", "Adjust in Viewport"): "Im Viewport anpassen",
        ("*", "Auto"): "Automatisch",
        ("*", "Auto Connectors"): "Automatische Verbinder",
        ("Operator", "Auto Connectors"): "Automatische Verbinder",
        ("*", "Axis"): "Achse",
        ("*", "Booleans"): "Boolesche Operationen",
        ("*", "both sides"): "beide Seiten",
        ("*", "Build"): "Erzeugen",
        ("Operator", "Build"): "Erzeugen",
        ("*", "Build & Export"): "Erzeugen & Exportieren",
        ("Operator", "Build & Export"): "Erzeugen & Exportieren",
        ("*", "Bump diameter (mm)"): "Noppendurchmesser (mm)",
        ("*", "Bump height (mm)"): "Noppenhöhe (mm)",
        ("*", "Bumps"): "Noppen",
        ("*", "Cannot build this cut:"): "Dieser Schnitt kann nicht erzeugt werden:",
        ("*", "Cap"): "Verschließen",
        ("*", "Chamfer (mm)"): "Fase (mm)",
        ("*", "Check Mesh"): "Mesh prüfen",
        ("Operator", "Check Mesh"): "Mesh prüfen",
        ("*", "Clear Build"): "Ergebnis entfernen",
        ("Operator", "Clear Build"): "Ergebnis entfernen",
        ("*", "Clear Stack"): "Stapel leeren",
        ("Operator", "Clear Stack"): "Stapel leeren",
        ("*", "Clearance (mm)"): "Spiel (mm)",
        ("*", "Click"): "Klicken",
        ("*", "Connector"): "Verbinder",
        ("*", "Connectors"): "Verbinder",
        ("Operator", "Connectors"): "Verbinder",
        ("*", "Count"): "Anzahl",
        ("*", "Custom"): "Eigen",
        ("*", "Custom mesh"): "Eigenes Mesh",
        ("*", "Cut"): "Schnitt",
        ("*", "Cylinder pin"): "Zylinderstift",
        ("*", "Debug log"): "Debug-Protokoll",
        ("*", "Direction"): "Richtung",
        ("*", "Distribute"): "Verteilen",
        ("*", "Distribution"): "Verteilung",
        ("*", "Dovetail"): "Schwalbenschwanz",
        ("*", "Dowel"): "Dübel",
        ("*", "Dowel (separate part)"): "Dübel (eigenes Teil)",
        ("*", "Down"): "Nach unten",
        ("*", "Draft"): "Entwurf",
        ("*", "Draw Cut"): "Schnitt zeichnen",
        ("*", "Duplicate Cut"): "Schnitt duplizieren",
        ("Operator", "Duplicate Cut"): "Schnitt duplizieren",
        ("*", "Easy"): "Einfach",
        ("*", "Easy Cut"): "Einfacher Schnitt",
        ("Operator", "Easy Cut"): "Einfacher Schnitt",
        ("*", "Editing the source's cuts"): "Bearbeitet die Schnitte der Quelle",
        ("*", "Enabled"): "Aktiv",
        ("*", "Explicit plane"): "Explizite Ebene",
        ("*", "Export Parts"): "Teile exportieren",
        ("Operator", "Export Parts"): "Teile exportieren",
        ("*", "Fast"): "Schnell",
        ("*", "Folder"): "Ordner",
        ("*", "Formats"): "Formate",
        ("*", "Gap (mm)"): "Fuge (mm)",
        ("*", "Grid"): "Raster",
        ("*", "Height (mm)"): "Höhe (mm)",
        ("*", "Index"): "Index",
        ("*", "Insert depth %"): "Einstecktiefe %",
        ("*", "Kind"): "Art",
        ("*", "Length (mm)"): "Länge (mm)",
        ("*", "Line"): "Linie",
        ("*", "Margin %"): "Rand %",
        ("*", "Material"): "Material",
        ("*", "Mesh"): "Mesh",
        ("*", "Mode"): "Modus",
        ("*", "Move Cut"): "Schnitt verschieben",
        ("Operator", "Move Cut"): "Schnitt verschieben",
        ("*", "New connector"): "Neuer Verbinder",
        ("*", "New connectors"): "Neue Verbinder",
        ("*", "Normal"): "Normale",
        ("*", "Offset (mm)"): "Versatz (mm)",
        ("*", "Origin"): "Ursprung",
        ("*", "Pin"): "Stift",
        ("*", "pin"): "Stift",
        ("*", "Pin on"): "Stift an",
        ("*", "Pin side"): "Stiftseite",
        ("*", "Place Connectors"): "Verbinder platzieren",
        ("Operator", "Place Connectors"): "Verbinder platzieren",
        ("*", "Plane"): "Ebene",
        ("*", "Point"): "Punkt",
        ("*", "Rectangular tenon"): "Rechteckzapfen",
        ("*", "Redraw in Viewport"): "Im Viewport neu zeichnen",
        ("*", "Remove Connector"): "Verbinder entfernen",
        ("Operator", "Remove Connector"): "Verbinder entfernen",
        ("*", "Remove Cut"): "Schnitt entfernen",
        ("Operator", "Remove Cut"): "Schnitt entfernen",
        ("*", "Replace"): "Ersetzen",
        ("*", "Result"): "Ergebnis",
        ("*", "Rotation"): "Drehung",
        ("*", "Rows"): "Reihen",
        ("*", "Select a mesh object"): "Ein Mesh-Objekt auswählen",
        ("*", "Settings"): "Einstellungen",
        ("Operator", "Settings"): "Einstellungen",
        ("*", "Show cuts in viewport"): "Schnitte im Viewport zeigen",
        ("*", "Smooth"): "Glätten",
        ("*", "Snap dovetail"): "Schnapp-Schwalbenschwanz",
        ("*", "Snap pin"): "Schnappstift",
        ("*", "Snap tenon"): "Schnappzapfen",
        ("*", "Snap to axis"): "An Achse ausrichten",
        ("*", "Stroke"): "Strich",
        ("*", "Tangent"): "Tangente",
        ("*", "Taper %"): "Verjüngung %",
        ("*", "Target"): "Ziel",
        ("*", "Tenon"): "Zapfen",
        ("*", "Type"): "Typ",
        ("*", "U (mm)"): "U (mm)",
        ("*", "Up"): "Nach oben",
        ("*", "Use Object Size"): "Objektgröße übernehmen",
        ("Operator", "Use Object Size"): "Objektgröße übernehmen",
        ("*", "V (mm)"): "V (mm)",
        ("*", "Width (mm)"): "Breite (mm)",
        ("*", "Write millimeters"): "In Millimetern schreiben",
        ("*", "1 unit = {mm} mm"): "1 Einheit = {mm} mm",
        ("*", "Gap {gap} mm, {n} connector(s)"): "Fuge {gap} mm, {n} Verbinder",
        ("*", "Part of {name}"): "Teil von {name}",
        ("*", "On {name}"): "Auf {name}",
        ("*", "{n} part(s) in {collection}"): "{n} Teil(e) in {collection}",
        ("Operator", "Cut"): "Schneiden",
        ("Operator", "Draw Cut"): "Schnitt zeichnen",
        ("Operator", "Redraw in Viewport"): "Im Viewport neu zeichnen",
        ("Operator", "Adjust in Viewport"): "Im Viewport anpassen",
        ("Operator", "Distribute"): "Verteilen",
        ("Operator", "Click"): "Klicken",
        ("Operator", "Rebuild"): "Neu erzeugen",
        # Phase 4: polyline / polygon cuts, print checks and fixes
        ("*", "Polyline"): "Polylinie",
        ("Operator", "Polyline"): "Polylinie",
        ("*", "Polygon"): "Polygon",
        ("*", "Cut Out"): "Ausschneiden",
        ("Operator", "Cut Out"): "Ausschneiden",
        ("*", "Depth (mm)"): "Tiefe (mm)",
        ("*", "Add Polyline Cut"): "Polylinienschnitt hinzufügen",
        ("Operator", "Add Polyline Cut"): "Polylinienschnitt hinzufügen",
        ("*", "Add Polygon Cut"): "Polygonschnitt hinzufügen",
        ("Operator", "Add Polygon Cut"): "Polygonschnitt hinzufügen",
        ("*", "Polyline: {n} points"): "Polylinie: {n} Punkte",
        ("*", "Polygon: {n} corners"): "Polygon: {n} Ecken",
        ("*", "Print checks"): "Druckprüfung",
        ("*", "Fix"): "Beheben",
        ("Operator", "Fix"): "Beheben",
        ("*", "Mesh not checked yet"): "Mesh noch nicht geprüft",
        ("*", "Rotation & scale applied"): "Drehung und Skalierung angewendet",
        ("*", "Closed (no holes)"): "Geschlossen (keine Löcher)",
        ("*", "{n} open edge(s), {m} loose"): "{n} offene Kante(n), {m} lose",
        ("*", "Normals point outward"): "Normalen zeigen nach außen",
        ("*", "No duplicate vertices"): "Keine doppelten Vertices",
        ("*", "{n} duplicate vertices"): "{n} doppelte Vertices",
        ("*", "{n} edge(s) with 3+ faces: fix in Edit Mode"): "{n} Kante(n) mit 3+ Flächen: im Bearbeitungsmodus beheben",
        ("*", "Apply Rotation & Scale"): "Drehung und Skalierung anwenden",
        ("Operator", "Apply Rotation & Scale"): "Drehung und Skalierung anwenden",
        ("*", "Set Units to Millimeters"): "Einheiten auf Millimeter setzen",
        ("Operator", "Set Units to Millimeters"): "Einheiten auf Millimeter setzen",
        ("*", "Recalculate Normals"): "Normalen neu berechnen",
        ("Operator", "Recalculate Normals"): "Normalen neu berechnen",
        ("*", "Merge by Distance"): "Nach Abstand zusammenführen",
        ("Operator", "Merge by Distance"): "Nach Abstand zusammenführen",
        ("*", "Fill Holes"): "Löcher füllen",
        ("Operator", "Fill Holes"): "Löcher füllen",
        ("*", "Distance (mm)"): "Abstand (mm)",
        ("*", "Objects"): "Objekte",
        ("*", "Keep Units"): "Einheiten beibehalten",
        ("*", "Keep Size"): "Größe beibehalten",
        ("*", "Polygon through the object: set a Depth for connectors on its floor"):
            "Polygon durch das ganze Objekt: Tiefe setzen für Verbinder auf seinem Boden",
    },
    "fr_FR": {
        ("*", "Auto"): "Auto",
        ("*", "Chamfer (mm)"): "Chanfrein (mm)",
        ("*", "Distribution"): "Répartition",
        ("*", "Dovetail"): "Queue d'aronde",
        ("*", "Grid"): "Grille",
        ("*", "Line"): "Ligne",
    },
    "es": {
        ("*", "Auto"): "Automático",
        ("*", "Chamfer (mm)"): "Chaflán (mm)",
        ("*", "Distribution"): "Distribución",
        ("*", "Dovetail"): "Cola de milano",
        ("*", "Grid"): "Cuadrícula",
        ("*", "Line"): "Línea",
    },
    "it_IT": {
        ("*", "Auto"): "Automatico",
        ("*", "Chamfer (mm)"): "Smusso (mm)",
        ("*", "Distribution"): "Distribuzione",
        ("*", "Dovetail"): "Coda di rondine",
        ("*", "Grid"): "Griglia",
        ("*", "Line"): "Linea",
    },
    "pt_BR": {
        ("*", "Auto"): "Automático",
        ("*", "Chamfer (mm)"): "Chanfro (mm)",
        ("*", "Distribution"): "Distribuição",
        ("*", "Dovetail"): "Rabo de andorinha",
        ("*", "Grid"): "Grade",
        ("*", "Line"): "Linha",
    },
    "pt_PT": {
        ("*", "Auto"): "Automático",
        ("*", "Chamfer (mm)"): "Chanfro (mm)",
        ("*", "Distribution"): "Distribuição",
        ("*", "Dovetail"): "Cauda de andorinha",
        ("*", "Grid"): "Grelha",
        ("*", "Line"): "Linha",
    },
    "nl_NL": {
        ("*", "Auto"): "Automatisch",
        ("*", "Chamfer (mm)"): "Afschuining (mm)",
        ("*", "Distribution"): "Verdeling",
        ("*", "Dovetail"): "Zwaluwstaart",
        ("*", "Grid"): "Raster",
        ("*", "Line"): "Lijn",
    },
    "pl_PL": {
        ("*", "Auto"): "Automatyczny",
        ("*", "Chamfer (mm)"): "Fazowanie (mm)",
        ("*", "Distribution"): "Rozmieszczenie",
        ("*", "Dovetail"): "Jaskółczy ogon",
        ("*", "Grid"): "Siatka",
        ("*", "Line"): "Linia",
    },
    "ja_JP": {
        ("*", "Auto"): "自動",
        ("*", "Chamfer (mm)"): "面取り (mm)",
        ("*", "Distribution"): "分布",
        ("*", "Dovetail"): "あり継ぎ",
        ("*", "Grid"): "グリッド",
        ("*", "Line"): "ライン",
    },
    "zh_HANS": {
        ("*", "Auto"): "自动",
        ("*", "Chamfer (mm)"): "倒角 (mm)",
        ("*", "Distribution"): "分布",
        ("*", "Dovetail"): "燕尾",
        ("*", "Grid"): "网格",
        ("*", "Line"): "直线",
    },
    "zh_HANT": {
        ("*", "Auto"): "自動",
        ("*", "Chamfer (mm)"): "倒角 (mm)",
        ("*", "Distribution"): "分佈",
        ("*", "Dovetail"): "燕尾",
        ("*", "Grid"): "網格",
        ("*", "Line"): "直線",
    },
    "ru_RU": {
        ("*", "Auto"): "Авто",
        ("*", "Chamfer (mm)"): "Фаска (мм)",
        ("*", "Distribution"): "Распределение",
        ("*", "Dovetail"): "Ласточкин хвост",
        ("*", "Grid"): "Сетка",
        ("*", "Line"): "Линия",
    },
    "uk_UA": {
        ("*", "Auto"): "Авто",
        ("*", "Distribution"): "Розподіл",
        ("*", "Dovetail"): "Ластівчин хвіст",
    },
    "tr_TR": {
        ("*", "Auto"): "Otomatik",
        ("*", "Distribution"): "Dağıtım",
        ("*", "Dovetail"): "Kırlangıç Kuyruğu",
    },
    "sl": {
        ("*", "Auto"): "Samodejno",
        ("*", "Chamfer (mm)"): "Faza (mm)",
        ("*", "Distribution"): "Porazdelitev",
        ("*", "Dovetail"): "Lastovičji rep",
        ("*", "Grid"): "Mreža",
        ("*", "Line"): "Črta",
    },
    "ko_KR": {
        ("*", "Stroke: {n} points"): "스트로크: 점 {n}개",
        ("*", "Dowel layout"): "도웰 배치",
        ("*", "Flat"): "눕혀서",
        ("*", "Upright"): "세워서",
        ("*", "At assembly position"): "조립 위치",
        ("*", "Accurate"): "정확",
        ("*", "Active connector"): "활성 커넥터",
        ("*", "Active cut"): "활성 컷",
        ("*", "Add a cut (X/Y/Z, stroke, polyline or polygon), then Build"): "컷을 추가(X/Y/Z, 스트로크, 폴리라인 또는 폴리곤)한 뒤 빌드",
        ("*", "Add Connector"): "커넥터 추가",
        ("Operator", "Add Connector"): "커넥터 추가",
        ("*", "Add Plane Cut"): "평면 컷 추가",
        ("Operator", "Add Plane Cut"): "평면 컷 추가",
        ("*", "Add Stroke Cut"): "스트로크 컷 추가",
        ("Operator", "Add Stroke Cut"): "스트로크 컷 추가",
        ("*", "Adjust Cut Plane"): "컷 평면 조정",
        ("Operator", "Adjust Cut Plane"): "컷 평면 조정",
        ("*", "Adjust in Viewport"): "뷰포트에서 조정",
        ("*", "Auto"): "자동",
        ("*", "Auto Connectors"): "자동 커넥터",
        ("Operator", "Auto Connectors"): "자동 커넥터",
        ("*", "Axis"): "축",
        ("*", "Booleans"): "불리언",
        ("*", "both sides"): "양쪽",
        ("*", "Build"): "빌드",
        ("Operator", "Build"): "빌드",
        ("*", "Build & Export"): "빌드 및 내보내기",
        ("Operator", "Build & Export"): "빌드 및 내보내기",
        ("*", "Bump diameter (mm)"): "돌기 지름 (mm)",
        ("*", "Bump height (mm)"): "돌기 높이 (mm)",
        ("*", "Bumps"): "돌기 수",
        ("*", "Cannot build this cut:"): "이 컷을 빌드할 수 없음:",
        ("*", "Cap"): "단면 막기",
        ("*", "Chamfer (mm)"): "모따기 (mm)",
        ("*", "Check Mesh"): "메시 검사",
        ("Operator", "Check Mesh"): "메시 검사",
        ("*", "Clear Build"): "빌드 지우기",
        ("Operator", "Clear Build"): "빌드 지우기",
        ("*", "Clear Stack"): "스택 비우기",
        ("Operator", "Clear Stack"): "스택 비우기",
        ("*", "Clearance (mm)"): "공차 (mm)",
        ("*", "Click"): "클릭",
        ("*", "Connector"): "커넥터",
        ("*", "Connectors"): "커넥터",
        ("Operator", "Connectors"): "커넥터",
        ("*", "Count"): "개수",
        ("*", "Custom"): "사용자",
        ("*", "Custom mesh"): "사용자 메시",
        ("*", "Cut"): "컷",
        ("*", "Cylinder pin"): "원기둥 핀",
        ("*", "Debug log"): "디버그 로그",
        ("*", "Direction"): "방향",
        ("*", "Distribute"): "자동 배치",
        ("*", "Distribution"): "분포",
        ("*", "Dovetail"): "도브테일",
        ("*", "Dowel"): "도웰",
        ("*", "Dowel (separate part)"): "도웰 (별도 파트)",
        ("*", "Down"): "아래로",
        ("*", "Draft"): "드래프트",
        ("*", "Draw Cut"): "컷 그리기",
        ("*", "Duplicate Cut"): "컷 복제",
        ("Operator", "Duplicate Cut"): "컷 복제",
        ("*", "Easy"): "간편",
        ("*", "Easy Cut"): "간편 컷",
        ("Operator", "Easy Cut"): "간편 컷",
        ("*", "Editing the source's cuts"): "원본의 컷을 편집 중",
        ("*", "Enabled"): "사용",
        ("*", "Explicit plane"): "평면 직접 지정",
        ("*", "Export Parts"): "파트 내보내기",
        ("Operator", "Export Parts"): "파트 내보내기",
        ("*", "Fast"): "빠름",
        ("*", "Folder"): "폴더",
        ("*", "Formats"): "형식",
        ("*", "Gap (mm)"): "틈 (mm)",
        ("*", "Grid"): "격자",
        ("*", "Height (mm)"): "높이 (mm)",
        ("*", "Index"): "인덱스",
        ("*", "Insert depth %"): "삽입 깊이 %",
        ("*", "Kind"): "종류",
        ("*", "Length (mm)"): "길이 (mm)",
        ("*", "Line"): "선",
        ("*", "Margin %"): "여백 %",
        ("*", "Material"): "재질",
        ("*", "Mesh"): "메시",
        ("*", "Mode"): "모드",
        ("*", "Move Cut"): "컷 이동",
        ("Operator", "Move Cut"): "컷 이동",
        ("*", "New connector"): "새 커넥터",
        ("*", "New connectors"): "새 커넥터",
        ("*", "Normal"): "법선",
        ("*", "Offset (mm)"): "오프셋 (mm)",
        ("*", "Origin"): "원점",
        ("*", "Pin"): "핀",
        ("*", "pin"): "핀",
        ("*", "Pin on"): "핀 위치",
        ("*", "Pin side"): "핀 쪽",
        ("*", "Place Connectors"): "커넥터 배치",
        ("Operator", "Place Connectors"): "커넥터 배치",
        ("*", "Plane"): "평면",
        ("*", "Point"): "점",
        ("*", "Rectangular tenon"): "사각 테논",
        ("*", "Redraw in Viewport"): "뷰포트에서 다시 그리기",
        ("*", "Remove Connector"): "커넥터 삭제",
        ("Operator", "Remove Connector"): "커넥터 삭제",
        ("*", "Remove Cut"): "컷 삭제",
        ("Operator", "Remove Cut"): "컷 삭제",
        ("*", "Replace"): "교체",
        ("*", "Result"): "결과",
        ("*", "Rotation"): "회전",
        ("*", "Rows"): "행",
        ("*", "Select a mesh object"): "메시 오브젝트를 선택하세요",
        ("*", "Settings"): "설정",
        ("Operator", "Settings"): "설정",
        ("*", "Show cuts in viewport"): "뷰포트에 컷 표시",
        ("*", "Smooth"): "다듬기",
        ("*", "Snap dovetail"): "스냅 도브테일",
        ("*", "Snap pin"): "스냅 핀",
        ("*", "Snap tenon"): "스냅 테논",
        ("*", "Snap to axis"): "축에 맞춤",
        ("*", "Stroke"): "스트로크",
        ("*", "Tangent"): "접선",
        ("*", "Taper %"): "테이퍼 %",
        ("*", "Target"): "대상",
        ("*", "Tenon"): "테논",
        ("*", "Type"): "종류",
        ("*", "U (mm)"): "U (mm)",
        ("*", "Up"): "위로",
        ("*", "Use Object Size"): "오브젝트 크기 사용",
        ("Operator", "Use Object Size"): "오브젝트 크기 사용",
        ("*", "V (mm)"): "V (mm)",
        ("*", "Width (mm)"): "폭 (mm)",
        ("*", "Write millimeters"): "밀리미터로 쓰기",
        ("*", "1 unit = {mm} mm"): "1 단위 = {mm} mm",
        ("*", "Gap {gap} mm, {n} connector(s)"): "틈 {gap} mm, 커넥터 {n}개",
        ("*", "Part of {name}"): "{name}의 파트",
        ("*", "On {name}"): "{name}에 배치",
        ("*", "{n} part(s) in {collection}"): "{collection}에 파트 {n}개",
        ("Operator", "Cut"): "자르기",
        ("Operator", "Draw Cut"): "컷 그리기",
        ("Operator", "Redraw in Viewport"): "뷰포트에서 다시 그리기",
        ("Operator", "Adjust in Viewport"): "뷰포트에서 조정",
        ("Operator", "Distribute"): "자동 배치",
        ("Operator", "Click"): "클릭",
        ("Operator", "Rebuild"): "다시 빌드",
        # Tooltips (Korean only)
        ("*", "Dovetail: how much narrower the tip is than the base, percent"): "도브테일: 끝이 밑동보다 좁은 정도, 백분율",
        ("*", "Perpendicular to world X"): "월드 X에 수직",
        ("*", "Perpendicular to world Y"): "월드 Y에 수직",
        ("*", "Perpendicular to world Z"): "월드 Z에 수직",
        ("*", "-1 = active connector"): "-1 = 활성 커넥터",
        ("*", "A point on the cut plane (object local space)"): "컷 평면 위의 한 점(오브젝트 로컬 공간)",
        ("*", "Add a planar cut to the stack"): "스택에 평면 컷을 추가",
        ("*", "Add one connector at (U, V) on the seam of the cut"): "컷 시임의 (U, V) 위치에 커넥터 하나 추가",
        ("*", "Any closed mesh object as the pin, scaled into width x height x length; the socket is its outline offset by the clearance"): "닫힌 메시 오브젝트를 핀으로 사용(폭 x 높이 x 길이로 크기 조정); 소켓은 그 외곽을 공차만큼 넓힌 형상",
        ("*", "Autodesk FBX"): "Autodesk FBX",
        ("*", "Bevel of the pin tip (dowel: both ends), eases insertion"): "핀 끝(도웰은 양 끝)의 모따기, 끼우기 쉬워짐",
        ("*", "Binary STL"): "바이너리 STL",
        ("*", "Boolean solver order for curved cuts and connectors; every result is validated"): "곡선 컷과 커넥터의 불리언 솔버 순서; 모든 결과를 검증함",
        ("*", "Box tenon of width x height (cannot rotate)"): "폭 x 높이의 사각 테논(돌아가지 않음)",
        ("*", "Build the enabled cuts into a result collection (the original object is not modified). With a built part selected, the source object's stack is built. Esc cancels a running build"): "사용 중인 컷으로 결과 컬렉션을 만든다(원본 오브젝트는 바뀌지 않음). 빌드된 파트를 선택하면 원본의 스택을 빌드한다. 진행 중에 Esc로 취소",
        ("*", "Clearance 0.10 mm"): "공차 0.10 mm",
        ("*", "Clearance 0.20 mm"): "공차 0.20 mm",
        ("*", "Clearance 0.25 mm"): "공차 0.25 mm",
        ("*", "Clearance 0.30 mm"): "공차 0.30 mm",
        ("*", "Clearance 0.35 mm"): "공차 0.35 mm",
        ("*", "Click on the seam of the active cut to place connectors (new-connector type and size)"): "활성 컷의 시임을 클릭해 커넥터 배치(새 커넥터 종류와 크기)",
        ("*", "Close the cut faces"): "잘린 단면을 막음",
        ("*", "Closed mesh used as the pin (custom connectors); its local Z is the insertion direction, lowest Z the embedded end"): "핀으로 쓰는 닫힌 메시(사용자 커넥터); 로컬 Z가 삽입 방향, 가장 낮은 Z가 박히는 끝",
        ("*", "Columns x rows over the seam, points outside the section are dropped"): "시임 위에 열 x 행, 단면 밖의 점은 버림",
        ("*", "Connectors along the line, or grid columns"): "선을 따라 놓을 커넥터 수, 또는 격자 열 수",
        ("*", "Curved cut: a drawn stroke extruded along the view direction"): "곡선 컷: 그린 스트로크를 뷰 방향으로 밀어낸 면",
        ("*", "Cut index (-1 = active cut)"): "컷 인덱스(-1 = 활성 컷)",
        ("*", "Cut plane normal (object local space)"): "컷 평면 법선(오브젝트 로컬 공간)",
        ("*", "Cylinder pin with snap bumps that click into dimples in the socket"): "소켓의 홈에 딸깍 끼는 스냅 돌기가 있는 원기둥 핀",
        ("*", "Default socket clearance per side"): "한쪽당 기본 소켓 공차",
        ("*", "Delete the built parts and show the original object again"): "빌드한 파트를 지우고 원본 오브젝트를 다시 표시",
        ("*", "Diameter of a snap bump"): "스냅 돌기의 지름",
        ("*", "Distance from the bounding box center along the axis"): "축을 따라 바운딩 박스 중심에서 떨어진 거리",
        ("*", "Distance kept from the seam edges, percent of its extent"): "시임 가장자리에서 띄울 거리, 시임 크기의 백분율",
        ("*", "Distance of the cut from the object's bounding box center"): "오브젝트 바운딩 박스 중심에서 컷까지의 거리",
        ("*", "Distribute connectors over the seam of the cut (Line or Grid), using the new-connector settings"): "새 커넥터 설정으로 컷 시임에 커넥터를 배치(선 또는 격자)",
        ("*", "Dowel parts lie along X next to the object (strongest print: layers run along the dowel)"): "도웰 파트를 오브젝트 옆에 X 방향으로 눕힘(가장 튼튼한 출력: 층이 도웰을 따라 쌓임)",
        ("*", "Dowel parts sit in their sockets (preview); Export writes them lying flat"): "도웰 파트를 소켓 안에 둠(미리보기); 내보내기는 눕힌 자세로 씀",
        ("*", "Dowel parts stand on an end next to the object (round section exact; weaker across the layers)"): "도웰 파트를 오브젝트 옆에 세움(원형 단면이 정확; 층 사이로는 약함)",
        ("*", "Draw a curved cut: the stroke is extruded along the view direction through the whole object (LMB draw, Enter confirm, Esc cancel, Shift at release: straight axis line)"): "곡선 컷 그리기: 스트로크를 뷰 방향으로 오브젝트 전체에 밀어냄(LMB 그리기, Enter 확정, Esc 취소, 놓을 때 Shift: 축 방향 직선)",
        ("*", "Duplicate a cut with its connectors"): "컷을 커넥터와 함께 복제",
        ("*", "Easy mode: add connectors and build immediately"): "간편 모드: 커넥터를 추가하고 바로 빌드",
        ("*", "Easy mode: add one axis cut (with connectors) to the stack and build immediately"): "간편 모드: 축 컷 하나(커넥터 포함)를 스택에 추가하고 바로 빌드",
        ("*", "Edit a stack of cuts, then Build"): "컷 스택을 편집한 뒤 빌드",
        ("*", "Evenly spaced along the longer extent of the seam"): "시임의 긴 방향을 따라 같은 간격으로",
        ("*", "Exact solver first (with self-intersection handling when shells intersect): intersecting shells, e.g. eyes set into a head, are united into one solid. Slow on large meshes"): "정확한 솔버 우선(셸이 교차하면 자기교차 처리): 교차하는 셸(예: 머리에 박힌 눈)을 하나의 솔리드로 합침. 큰 메시에서 느림",
        ("*", "Export every built part of the active object to its own file"): "활성 오브젝트의 빌드된 파트를 각각 파일로 내보내기",
        ("*", "Extrusion (view) direction, world space"): "밀어내기(뷰) 방향, 월드 공간",
        ("*", "Extrusion direction of the stroke (object local space)"): "스트로크를 밀어내는 방향(오브젝트 로컬 공간)",
        ("*", "Fast on meshes over 200,000 faces, Accurate below"): "면이 200,000개를 넘으면 빠름, 그 아래는 정확",
        ("*", "File formats (none = scene setting)"): "파일 형식(없음 = 씬 설정)",
        ("*", "Grid rows"): "격자 행 수",
        ("*", "How far a snap bump stands out of the pin surface"): "스냅 돌기가 핀 표면에서 튀어나온 높이",
        ("*", "Manifold solver first, much faster on large meshes, but intersecting shells stay overlapping (each is cut on its own; slicers unite them). Falls back to Accurate on failure"): "Manifold 솔버 우선, 큰 메시에서 훨씬 빠르지만 교차하는 셸은 겹친 채로 남음(각각 따로 잘림; 슬라이서가 합침). 실패하면 정확 순서로",
        ("*", "Material removed along an Easy cut (kerf)"): "간편 컷을 따라 깎아낼 두께(톱날 폭)",
        ("*", "Material removed along the cut (kerf)"): "컷을 따라 깎아낼 두께(톱날 폭)",
        ("*", "Move a cut up or down (cuts are applied top to bottom)"): "컷을 위아래로 이동(컷은 위에서 아래 순서로 적용)",
        ("*", "Move or re-orient a cut plane in the viewport"): "뷰포트에서 컷 평면을 이동하거나 방향을 바꿈",
        ("*", "One click: add an axis cut and build immediately"): "한 번에: 축 컷을 추가하고 바로 빌드",
        ("*", "Pin diameter (cylinder) or tenon width"): "핀 지름(원기둥) 또는 테논 폭",
        ("*", "Pins added along the seam (0 = none)"): "시임을 따라 추가할 핀 수(0 = 없음)",
        ("*", "Pins on the seam (-1 = scene setting)"): "시임의 핀 수(-1 = 씬 설정)",
        ("*", "Planar cut"): "평면 컷",
        ("*", "Plane normal (object local space)"): "평면 법선(오브젝트 로컬 공간)",
        ("*", "Point on the plane (object local space)"): "평면 위의 점(오브젝트 로컬 공간)",
        ("*", "Position along normal x tangent, millimeters from the cut origin"): "법선 x 접선 방향 위치, 컷 원점에서 mm",
        ("*", "Position along the seam tangent, millimeters from the cut origin"): "시임 접선 방향 위치, 컷 원점에서 mm",
        ("*", "Print detailed debug messages to the system console"): "시스템 콘솔에 자세한 디버그 메시지 출력",
        ("*", "Rectangular tenon with snap bumps"): "스냅 돌기가 있는 사각 테논",
        ("*", "Redraw this stroke cut instead of adding a new one"): "새로 추가하지 않고 이 스트로크 컷을 다시 그림",
        ("*", "Remove a connector from the cut"): "컷에서 커넥터 삭제",
        ("*", "Remove a cut from the stack"): "스택에서 컷 삭제",
        ("*", "Remove all cuts from the stack"): "스택의 모든 컷 삭제",
        ("*", "Remove the cut's existing connectors"): "컷의 기존 커넥터 삭제",
        ("*", "Resample and smooth the points (off: they were prepared already)"): "점을 다시 샘플링하고 다듬음(끄면: 이미 준비된 점)",
        ("*", "Rotation around the cut normal, degrees"): "컷 법선을 축으로 한 회전, 도",
        ("*", "Round pin; width is the diameter"): "둥근 핀; 폭이 지름",
        ("*", "Scale so that file units are millimeters (what slicers expect)"): "파일 단위가 밀리미터가 되도록 크기 조정(슬라이서가 기대하는 단위)",
        ("*", "Seam frame U axis (projected into the plane)"): "시임 프레임 U축(평면에 투영)",
        ("*", "Set width, height and length of a custom connector to its mesh object's size (mm)"): "사용자 커넥터의 폭, 높이, 길이를 메시 오브젝트 크기(mm)로 설정",
        ("*", "Share of the length that sits inside the pin part (the rest sticks out into the socket); dowels always use 50 %"): "핀 파트 안에 박히는 길이의 비율(나머지는 소켓으로 튀어나옴); 도웰은 항상 50 %",
        ("*", "Snap bumps evenly around the pin"): "핀 둘레에 고르게 놓을 스냅 돌기 수",
        ("*", "Socket clearance per side; -1 uses the scene default"): "한쪽당 소켓 공차; -1이면 씬 기본값",
        ("*", "Sockets in both parts and a separate printable dowel part"): "두 파트 모두에 소켓, 그리고 따로 출력할 도웰 파트",
        ("*", "Stable identifier written onto built parts"): "빌드한 파트에 기록되는 고정 식별자",
        ("*", "Straighten the stroke and align it with the nearest world axis in the view"): "스트로크를 곧게 펴서 뷰에서 가장 가까운 월드 축에 맞춤",
        ("*", "Stroke points in world space (scripts; the modal fills them)"): "월드 공간의 스트로크 점(스크립트용; 모달이 채움)",
        ("*", "Tapered tenon with snap bumps"): "스냅 돌기가 있는 테이퍼 테논",
        ("*", "Tapered tenon: narrower towards the tip, self-centering"): "테이퍼 테논: 끝으로 갈수록 좁아져 저절로 중심이 맞음",
        ("*", "Target folder (empty = scene setting)"): "대상 폴더(비우면 씬 설정)",
        ("*", "Tenon height (rectangular tenon only)"): "테논 높이(사각 테논만)",
        ("*", "The active connector of the active cut"): "활성 컷의 활성 커넥터",
        ("*", "The new-connector settings"): "새 커넥터 설정",
        ("*", "The pin sits on the part on the negative side of the cut normal"): "핀이 컷 법선의 음(-) 쪽 파트에 붙음",
        ("*", "The pin sits on the part on the positive side of the cut normal"): "핀이 컷 법선의 양(+) 쪽 파트에 붙음",
        ("*", "Total pin (or dowel) length; Insert depth % of it sits in the pin part"): "핀(또는 도웰)의 전체 길이; 그중 삽입 깊이 %가 핀 파트 안에 박힘",
        ("*", "Type and size of connectors added by Distribute or clicking"): "자동 배치나 클릭으로 추가할 커넥터의 종류와 크기",
        ("*", "Use Origin/Normal (object local space) instead of Axis/Offset"): "축/오프셋 대신 원점/법선(오브젝트 로컬 공간) 사용",
        ("*", "Wavefront OBJ"): "Wavefront OBJ",
        ("*", "Where Build puts the separate dowel parts"): "빌드가 별도 도웰 파트를 놓을 위치",
        ("*", "World X"): "월드 X",
        ("*", "World Y"): "월드 Y",
        ("*", "World Z"): "월드 Z",
        # Phase 4: polyline / polygon cuts, print checks and fixes
        ("*", "Polyline"): "폴리라인",
        ("Operator", "Polyline"): "폴리라인",
        ("*", "Polygon"): "폴리곤",
        ("*", "Cut Out"): "도려내기",
        ("Operator", "Cut Out"): "도려내기",
        ("*", "Depth (mm)"): "깊이 (mm)",
        ("*", "Add Polyline Cut"): "폴리라인 컷 추가",
        ("Operator", "Add Polyline Cut"): "폴리라인 컷 추가",
        ("*", "Add Polygon Cut"): "폴리곤 컷 추가",
        ("Operator", "Add Polygon Cut"): "폴리곤 컷 추가",
        ("*", "Polyline: {n} points"): "폴리라인: 점 {n}개",
        ("*", "Polygon: {n} corners"): "폴리곤: 꼭짓점 {n}개",
        ("*", "Print checks"): "출력 검사",
        ("*", "Fix"): "수정",
        ("Operator", "Fix"): "수정",
        ("*", "Mesh not checked yet"): "메시를 아직 검사하지 않음",
        ("*", "Rotation & scale applied"): "회전·스케일 적용됨",
        ("*", "Closed (no holes)"): "닫힘(구멍 없음)",
        ("*", "{n} open edge(s), {m} loose"): "열린 모서리 {n}개, 떨어진 요소 {m}개",
        ("*", "Normals point outward"): "법선이 바깥을 향함",
        ("*", "No duplicate vertices"): "중복 정점 없음",
        ("*", "{n} duplicate vertices"): "중복 정점 {n}개",
        ("*", "{n} edge(s) with 3+ faces: fix in Edit Mode"): "면이 3개 이상인 모서리 {n}개: 편집 모드에서 수정",
        ("*", "Apply Rotation & Scale"): "회전·스케일 적용",
        ("Operator", "Apply Rotation & Scale"): "회전·스케일 적용",
        ("*", "Set Units to Millimeters"): "단위를 밀리미터로 설정",
        ("Operator", "Set Units to Millimeters"): "단위를 밀리미터로 설정",
        ("*", "Recalculate Normals"): "법선 다시 계산",
        ("Operator", "Recalculate Normals"): "법선 다시 계산",
        ("*", "Merge by Distance"): "거리로 병합",
        ("Operator", "Merge by Distance"): "거리로 병합",
        ("*", "Fill Holes"): "구멍 채우기",
        ("Operator", "Fill Holes"): "구멍 채우기",
        ("*", "Distance (mm)"): "거리 (mm)",
        ("*", "Objects"): "오브젝트",
        ("*", "Keep Units"): "단위 유지",
        ("*", "Keep Size"): "크기 유지",
        ("*", "Polygon through the object: set a Depth for connectors on its floor"):
            "오브젝트를 관통하는 폴리곤: 바닥에 커넥터를 두려면 깊이를 설정하세요",
        # Phase 4 tooltips
        ("*", "Apply the object's rotation and scale to its mesh; the cuts move with it, so they stay in place"):
            "오브젝트의 회전과 스케일을 메시에 적용합니다. 컷도 함께 옮겨지므로 제자리에 남습니다",
        ("*", "Check the source mesh for printing: holes and non-manifold edges, loose geometry, normals, duplicate "
              "vertices, applied transforms, mm units (results and Fix buttons in the panel)"):
            "원본 메시를 출력용으로 검사합니다: 구멍과 비매니폴드 모서리, 떨어진 지오메트리, 법선, 중복 정점, 적용된 변환, "
            "mm 단위(결과와 수정 버튼은 패널에 표시)",
        ("*", "Click points for a cut along straight segments, extruded along the view direction through the whole "
              "object (LMB add point, Ctrl: 15 degree steps, Backspace remove last, Enter confirm, Esc cancel)"):
            "직선 구간을 따라 자를 점들을 클릭합니다. 뷰 방향으로 오브젝트 전체를 관통하게 압출됩니다(LMB 점 추가, "
            "Ctrl: 15도 단위, Backspace 마지막 점 삭제, Enter 확정, Esc 취소)",
        ("*", "Click the corners of a region to cut it out as its own part (a prism along the view direction, "
              "through the object or Depth deep; LMB add point, click the first point or Enter to close, Backspace "
              "remove last, Esc cancel)"):
            "영역의 꼭짓점을 클릭해 그 영역을 별도 파트로 도려냅니다(뷰 방향 프리즘, 오브젝트 관통 또는 깊이만큼; "
            "LMB 점 추가, 첫 점 클릭이나 Enter로 닫기, Backspace 마지막 점 삭제, Esc 취소)",
        ("*", "Cut along straight segments between clicked points, extruded along the view direction"):
            "클릭한 점 사이의 직선 구간을 따라 자르는 컷, 뷰 방향으로 압출",
        ("*", "Cut out the region inside a clicked closed polygon (a prism along the view direction, through the "
              "object or Depth deep) as its own part"):
            "클릭한 닫힌 폴리곤 안의 영역을 별도 파트로 도려냅니다(뷰 방향 프리즘, 오브젝트 관통 또는 깊이만큼)",
        ("*", "Easy polygon cut-out: how deep it reaches into the object from its front along the view (0 = through "
              "the whole object, no connectors)"):
            "Easy 폴리곤 도려내기: 뷰 방향으로 오브젝트 앞면에서 얼마나 깊이 들어가는지(0 = 오브젝트 전체 관통, 커넥터 없음)",
        ("*", "Fill the holes of the source mesh and delete loose vertices and edges (edges with more than two faces "
              "are left for Edit Mode)"):
            "원본 메시의 구멍을 채우고 떨어진 정점과 모서리를 삭제합니다(면이 셋 이상인 모서리는 편집 모드에서 직접 수정)",
        ("*", "How deep the cut-out reaches from the object's front along the view (0 = through the whole object; "
              "-1 = keep the redrawn cut's depth, Easy: the Easy depth, otherwise 0)"):
            "도려낸 영역이 뷰 방향으로 오브젝트 앞면에서 얼마나 깊이 들어가는지(0 = 오브젝트 전체 관통; -1 = 다시 그리는 "
            "컷의 깊이 유지, Easy는 Easy 깊이, 그 밖에는 0)",
        ("*", "Keep the objects as they are: 1 unit becomes 1 mm (right after importing an STL in millimeters into a "
              "meter scene)"):
            "오브젝트를 그대로 둡니다: 1 단위가 1 mm가 됩니다(밀리미터 STL을 미터 씬에 가져온 직후에 알맞음)",
        ("*", "Merge vertices of the source mesh closer than the distance (Merge by Distance)"):
            "원본 메시에서 거리보다 가까운 정점들을 병합합니다(거리로 병합)",
        ("*", "Points in world space (scripts; the modal fills them)"):
            "월드 공간의 점(스크립트용; 모달이 채움)",
        ("*", "Polygon cuts: how deep the cut-out reaches into the object from its front along the view direction "
              "(0 = through the whole object); connectors sit on the floor of a cut-out with a depth"):
            "폴리곤 컷: 도려낸 영역이 뷰 방향으로 오브젝트 앞면에서 얼마나 깊이 들어가는지(0 = 오브젝트 전체 관통); "
            "깊이가 있으면 커넥터는 도려낸 영역의 바닥에 놓임",
        ("*", "Recalculate the source mesh's face normals to point outward"):
            "원본 메시의 면 법선이 바깥을 향하도록 다시 계산합니다",
        ("*", "Redraw this cut instead of adding a new one"): "새로 추가하지 않고 이 컷을 다시 그림",
        ("*", "Scale every object in the scene so its physical size stays the same (a model built in meters keeps "
              "its millimeter size); apply the scale afterwards"):
            "씬의 모든 오브젝트를 스케일해 실제 크기를 유지합니다(미터로 만든 모델이 같은 밀리미터 크기를 유지); "
            "그 뒤 스케일을 적용하세요",
        ("*", "Set the scene to Metric, Millimeters and Unit Scale 0.001 (1 unit = 1 mm, what slicers expect)"):
            "씬을 Metric, Millimeters, Unit Scale 0.001로 설정합니다(1 단위 = 1 mm, 슬라이서가 기대하는 값)",
        ("*", "Stroke / polyline / polygon points (object local space)"):
            "스트로크 / 폴리라인 / 폴리곤 점(오브젝트 로컬 공간)",
        ("*", "Vertices closer than this are merged"): "이보다 가까운 정점은 병합됩니다",
    },
    "sw": {
        ("*", "Auto"): "Otomatiki",
        ("*", "Chamfer (mm)"): "Ukingo ulionyooshwa (mm)",
        ("*", "Distribution"): "Usambazaji",
        ("*", "Dovetail"): "Dovetail",
        ("*", "Grid"): "Gridi",
        ("*", "Line"): "Mstari",
    },
    "ar_EG": {
        ("*", "Auto"): "تلقائي",
        ("*", "Chamfer (mm)"): "الشطف (مم)",
        ("*", "Distribution"): "التوزيع",
        ("*", "Dovetail"): "ذيل الحمامة",
        ("*", "Grid"): "شبكة",
        ("*", "Line"): "خط",
    },
    "fa_IR": {
        ("*", "Auto"): "خودکار",
        ("*", "Chamfer (mm)"): "پخ (mm)",
        ("*", "Distribution"): "توزیع",
        ("*", "Dovetail"): "دم‌چلچله‌ای",
        ("*", "Grid"): "شبکه",
        ("*", "Line"): "خط",
    },
    "hi_IN": {
        ("*", "Auto"): "स्वचालित",
        ("*", "Chamfer (mm)"): "चम्फर (मिमी)",
        ("*", "Distribution"): "वितरण",
        ("*", "Dovetail"): "डवटेल",
        ("*", "Grid"): "ग्रिड",
        ("*", "Line"): "रेखा",
    },
}
